title     = "Matt Snider"
baseURL   = "https://matt-snider.github.io/"
copyright = "© 2024 Matt Snider"

[markup]
  [markup.highlight]
    codeFences = false

[params]
    full_name = "Matt Snider"
    job_title = "Software Developer"

    [params.social]
    github_url  = "https://github.com/matt-snider"
    gitlab_url  = "https://gitlab.com/matt-snider"
    personal_url= "https://matt-snider.xyz"

    # Usually don't want to specify these
    email       = "[myfirstname].[mylastname]@protonmail.com"
    phone       = "Ask me"
    address     = "Bremen, Germany"

    [params.navigation]
    about    = "About"
    projects = "Projects"
    resume = "CV"

